DROP DATABASE IF EXISTS PTS;

CREATE DATABASE PTS;

DROP TABLE IF EXISTS USERS;

create table USERS
(
    ID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    HEIGHT INT NOT NULL,
    WEIGHT INT NOT NULL,
    BIRTH_YEAR INT NOT NULL,
    GENDER BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS MEASURES;

create table MEASURES
(
    ID INT AUTO_INCREMENT,
    UID VARCHAR(20) NOT NULL,
    SIT_UP INT NOT NULL,
    PUSH_UP INT NOT NULL,
    SQUAT INT NOT NULL,
    RUNNING_JUMP INT NOT NULL,
    STANDING_JUMP INT NOT NULL,
    TWIST_SIT_UP INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USERS_MEASURES FOREIGN KEY (UID) REFERENCES USERS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS RESULTS;

create table RESULTS
(
    ID INT AUTO_INCREMENT,
    UID VARCHAR(20) NOT NULL,
    BMI VARCHAR(5) NOT NULL,
    ARM INT NOT NULL,
    LEG INT NOT NULL,
    CORE INT NOT NULL,
    CHEST INT NOT NULL,
    FAT VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USERS_RESULTS FOREIGN KEY (UID) REFERENCES USERS (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);